version: '3.1'
services:
  piping:
    image: nwtgck/piping-server:v1.12.0
    restart: always
    command: ["--http-port=80"]
    expose:
      - "80"

  nginx:
    image: nginx:1.21-alpine
    ports:
      - '8080:80'
    depends_on:
      - piping
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
